# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iLeetcode' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iLeetcode
  pod 'BaiduMobStatCodeless' #无埋点SDK
  #pod 'PPSnapshotKit'

  target 'iLeetcodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iLeetcodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
